global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: '${ALERT_EMAIL_FROM}'
  smtp_auth_username: '${ALERT_EMAIL_FROM}'
  smtp_auth_password: '${ALERT_EMAIL_PASSWORD}'

route:
  group_by: [ 'alertname' ]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email'
  routes:
  - match:
      severity: critical
    receiver: 'slack'

receivers:
- name: 'email'
  email_configs:
  - to: '${ALERT_EMAIL_TO}'
    send_resolved: true

- name: 'slack'
  slack_configs:
  - api_url: '${SLACK_WEBHOOK_URL}'
    channel: '#alerts'
    send_resolved: true
